# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginPage(object):
    def setupUi(self, LoginPage):
        LoginPage.setObjectName("LoginPage")
        LoginPage.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=LoginPage)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(parent=LoginPage)
        self.label.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=LoginPage)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=LoginPage)
        self.label_3.setGeometry(QtCore.QRect(110, 20, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.username = QtWidgets.QLineEdit(parent=LoginPage)
        self.username.setGeometry(QtCore.QRect(100, 70, 241, 31))
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(parent=LoginPage)
        self.password.setGeometry(QtCore.QRect(100, 120, 241, 31))
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setObjectName("password")

        self.retranslateUi(LoginPage)
        self.buttonBox.accepted.connect(LoginPage.accept) # type: ignore
        self.buttonBox.rejected.connect(LoginPage.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginPage)

    def retranslateUi(self, LoginPage):
        _translate = QtCore.QCoreApplication.translate
        LoginPage.setWindowTitle(_translate("LoginPage", "Dialog"))
        self.label.setText(_translate("LoginPage", "Username"))
        self.label_2.setText(_translate("LoginPage", "Password"))
        self.label_3.setText(_translate("LoginPage", "Login Page"))
